### PR TITLE
Fixes issue 66

### LINKED ISSUE #66: OracleBase inccorectly assumes that the tableName does not hold the schema too.
## Describe the Bug
When the driver tries to auto-increment the sequence, the table variable can hold the Schema. So, 
```
select sequence_name from user_tab_identity_cols where table_name='$tableName' and column_name='$columnName'
```
comes back with no result since the table_name isn't expecting the Schema too. The other issue with the above is that it expects that the user to have a sequence for it that it may not.

## To reproduce
Have a database setup that has a user with access to another Schema that is not its own. In the app_local config, set the schema to that one and the username to the user that has access to it. Make sure autoincrement is set to true and try to save a new item into a table without stating what its primary key should be set to. When it tries to do the first query in [this function](https://github.com/CakeDC/cakephp-oracle-driver/blob/612d3e732ae6f3234711035e73bcd2dca6b5e765/src/Database/Driver/OracleBase.php#L391) then it should return a result that is false.

## Expected behavior
I expect the result to not be false because the sequence does exists, but it's table_name does not include the schema.

## Impact on your work
The function does not work as intended and does not allow me to insert a new item into the table.

## Additional context
This could probably be fixed in [the `lastInsertId` function](https://github.com/CakeDC/cakephp-oracle-driver/blob/612d3e732ae6f3234711035e73bcd2dca6b5e765/src/Database/Driver/OracleBase.php#L300) and just have the schema passed to the `_autoincrementSequenceId` function.

### PR DESCRIPTION
**Pull request by Tyl13**
Resolve #66.

### CODE REVIEW

File: src/Database/Driver/OracleBase.php [hunk 1]
```diff
@@ -290,8 +290,9 @@ public function convertPositionalToNamedPlaceholders($query)
      */
     public function lastInsertId(?string $table = null, ?string $column = null)
     {
+        [$schema, $table] = explode('.', $table);
```
Comment (ctgraham) [inline src/Database/Driver/OracleBase.php:293]: This is a breaking change if the passed in `$table` is only the tablename and not `schema.table`.

File: src/Database/Driver/OracleBase.php [hunk 2]
```diff
@@ -388,14 +390,14 @@ protected function _autoincrementSequenceId(?string $table, ?string $column)
...
-        $query = "select sequence_name from user_tab_identity_cols where table_name='$tableName' and column_name='$columnName'";
+        $query = "select sequence_name from all_tab_identity_cols where table_name='$tableName' and column_name='$columnName'";
         $this->connect();
         $seqStatement = $this->_connection->query($query);
         $result = $seqStatement->fetch(PDO::FETCH_NUM);
 
         $sequenceName = $result[0];
 
-        $statement = $this->_connection->query("SELECT {$sequenceName}.CURRVAL FROM DUAL");
+        $statement = $this->_connection->query("SELECT {$schema}.{$sequenceName}.CURRVAL FROM DUAL");
```
Comment (ctgraham) [inline src/Database/Driver/OracleBase.php:400]: If `$schema` is an optional parameter, we cannot presume it to be set here.

**Review by ctgraham — CHANGES_REQUESTED** [review]
This introduces breaking changes for the legacy function of passing simple table names.

File: src/Database/Driver/OracleBase.php (hunk 2 above)
Comment (Tyl13) [reply src/Database/Driver/OracleBase.php]: This is fixed by checking if the schema is set. 
If it is then the new statement is called, if its not then the original is called.

File: src/Database/Driver/OracleBase.php (hunk 1 above)
Comment (Tyl13) [reply src/Database/Driver/OracleBase.php:293]: This is fixed by checking if table is set, and if its not then setting table to schema then schema to null.

File: src/Database/Driver/OracleBase.php [hunk 3]
```diff
@@ -377,25 +382,37 @@ public function prepareMethod($queryString, $options = [])
      *
      * @param string $table Table name.
      * @param string $column Column name
+     * @param string $schema Schema name
      * @return int
      */
-    protected function _autoincrementSequenceId(?string $table, ?string $column)
+    protected function _autoincrementSequenceId(?string $table, ?string $column, ?string $schema)
     {
+        $schemaExists = isset($schema);
```
Comment (ctgraham) [inline src/Database/Driver/OracleBase.php:390]: The introduction of this `$schemaExists` flag raises some maintainability risk.  Conditional logic is performed in the `if ($this->isAutoQuotingEnabled())` statement which may alter the `$schema` variable.  If a future change looks up the schema in the `if` or `else` condition, it would be responsible for updating the `$schemaExists` flag.

The existing pattern appears to be: take in option parameters as arguments (`$table`, `$column`), then assign them to trusted variables (`$tableName`, `$columnName`) which can be used in the SQL queries.  Instead of introducing a new flag variable, follow that convention to created a trusted `$schemaName` variable, which is check via `isset()` as needed.

**Review by ctgraham — CHANGES_REQUESTED** [review]
Please refactor away from the `$schemaExists` variable.

File: src/Database/Driver/OracleBase.php (hunk 3 above)
Comment (Tyl13) [reply src/Database/Driver/OracleBase.php:390]: Would it be better to just move it to after the conditional logic. While they do use isset or empty within if statements. Others like the `if ($this->isAutoQuotingEnabled())` is just returning a boolean, and in the construct statement of OCI8Connection they do a very similar thing with setting `$persistent = !empty($options['persistent']);` and then a little bit down checking `if ($persistent)`. 

They also don't have much consistency because the very next line of code is `if ($charset !== null)` and the charset was set right after persistent with `$charset = !empty($options['charset']) ? $options['charset'] : null;`.  So, I'm not sure which would be better. I was just trying to make sure the code wouldn't be repeating itself for a simple check.

Comment (ctgraham) [reply src/Database/Driver/OracleBase.php:390]: The convenience variables of `$persistent`, `$charset`, etc. in `OCI8Connection::_construct()` take a complex logic statement and condense it to a single readable variable.  The function also treats these as immutable; it has no incentive or business modifying the `$options[]` array.

In the examples here, the arguments are deliberately modified: optional, `strtoupper`, etc.  Introducing the convenience variable introduces the cognitive load of also keeping it current as changes occur (or enforcing that it is only set after the last change has occurred).

I agree that there isn't a ton of internal consistency here, but adding the convenience variable is also a clear move away from the immediate consistency of the surrounding code, without any real wins in aligning it with broader consistency across other files.

One other tangential thought: is there precedent for preferring:
```
        if ($schemaExists) {
            $query = "select sequence_name from all_tab_identity_cols where table_name='$tableName' and column_name='$columnName' and owner='$schema'";
        } else {
            $query = "select sequence_name from all_tab_identity_cols where table_name='$tableName' and column_name='$columnName'";
        }
```
over
```
        $query = "select sequence_name from all_tab_identity_cols where table_name='$tableName' and column_name='$columnName'";
        if ($schemaExists) {
            $query. =  and owner='$schema'";
        }
```

The latter reduces duplicate code, but some projects may prefer duplication in favor of more readable SQL.

Comment (Tyl13) [reply src/Database/Driver/OracleBase.php:390]: I understand what you are saying, I will change it to use the isset since their is no clear advantage. 

Additionally no, I had no preference. I was just doing it that way since the next time I use schema, it wasn't easily broken apart here
```php
if ($schemaExists) {
      $statement = $this->_connection->query("SELECT {$schemaName}.{$sequenceName}.CURRVAL FROM DUAL");
} else {
      $statement = $this->_connection->query("SELECT {$sequenceName}.CURRVAL FROM DUAL");
}
```
Additionally, the getDSN function combines multiple strings together 
```php
return '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=' . $config['host'] . ')(PORT=' . $config['port'] . '))' . '(CONNECT_DATA=(' . $service . ')' . $instance . $pooled . '))';```
So, I think I will break it out like in your suggestion. This leads to another question, should my second if statement be changed to be similar to the first. As in, 
```php
$query = "SELECT ";
if (isset($schemaName)) {
     $query .= "{$schemaName}.";
}
$query .= "{$sequenceName}.CURRVAL FROM DUAL";
$statement = $this->_connection->query($query);
```. This is how the query that you referenced works, so I'm not sure why it was changed for the second one.

Comment (ctgraham) [reply src/Database/Driver/OracleBase.php:390]: I'd default a ternary, personally
```
"SELECT ".(isset($schemaName) ? "{$schemaName}." : "")."{$sequenceName}.CURRVAL FROM DUAL"
```

**Review by ctgraham — APPROVED** [review]
Looks fit for purpose and backwards compatible.

**Review by stiliyanaa — COMMENTED** [review]
composer.lock

**Review by stiliyanaa — COMMENTED** [review]
composer.lock
src/Database/Driver/OracleBase.php
